import assert from 'node:assert/strict'
import test from 'node:test'
import { associateEvents } from '../dist/event-association.js'
import { EVENT_PROJECTION_STRATEGIES, projectActivity, projectTarget } from '../dist/event-projection.js'
import { history, compact, detail } from './fixtures/association.mjs'

const model = associateEvents(history)
const activity = seq => model.activityBySeq.get(seq)
const options = (base, evidence = {}) => ({ ...base, evidence })

test('Step identity, executed arguments, direct parallel PTC tree and independent outcomes share both densities', () => {
  const step = activity(20)
  const small = projectActivity(model, step, options(compact, { coverageComplete: true, pageSourceSeqs: [20, 21] }))
  const large = projectActivity(model, step, options(detail, { coverageComplete: true, pageSourceSeqs: [20, 21] }))
  assert.equal(small.activity_id, 'step:1:1')
  assert.equal(small.activity_id, large.activity_id)
  assert.deepEqual(small.source_seqs, large.source_seqs)
  assert.deepEqual(small.page_source_seqs, [20, 21])
  assert.ok(!small.source_seqs.includes(23))
  assert.equal(small.tools.length, 3)
  const root = small.tools.find(tool => tool.call_id === 'root')
  assert.equal(root.arguments, 'execution arguments')
  assert.equal(root.is_error, false)
  assert.deepEqual(root.children.map(tool => tool.call_id), ['a', 'b'])
  assert.equal(root.children[0].result_seq, 28)
  assert.equal(root.children[1].result_seq, 26)
  assert.equal(root.children[0].children[0].parent_call_id, 'a')
  assert.equal(root.children[0].children[0].error_code, 'FS_NOT_FOUND')
  assert.equal(root.children[0].children[0].is_error, true)
  assert.deepEqual(root.children[0].children[0].source_seqs, [25, 27])
  assert.equal(small.tools.find(tool => tool.call_id === 'undispatched').execution_observed, false)
  assert.ok(small.incomplete_reasons.includes('execution_not_observed'))
  assert.equal(small.complete, false)
  assert.equal(small.truncated, true)
  assert.equal(small.records.find(record => record.seq === 12).empty, true)
  const changes = small.records.find(record => record.seq === 14)
  assert.equal(changes.headerSeq, 9)
  assert.deepEqual(changes.preview.content.map(block => block.type), ['tool-addition', 'tool-removal'])
  assert.equal(activity(70).kind, 'ptc-fragment')
  assert.notEqual(activity(70), activity(71))
})

test('target is just one pair and known locators, independent of density and PTC fanout', () => {
  for (const view of [compact, detail]) {
    const child = projectTarget(model, 27, view)
    assert.equal(child.requested_seq, 27)
    assert.deepEqual(child.source_seqs, [25, 27])
    assert.deepEqual(child.tools.map(tool => tool.call_id), ['nested'])
    assert.equal(child.tools[0].children, undefined)
    assert.equal(child.tools[0].arguments.file_path, 'missing')
    assert.equal(child.activity_locator.root_call_id, 'root')
    assert.equal(child.activity_locator.activity_id, 'step:1:1')
    assert.equal(child.complete, true)
    const root = projectTarget(model, 40, view)
    assert.deepEqual(root.source_seqs, [20, 21, 40])
    assert.equal(root.tools[0].children, undefined)
    assert.ok(!root.source_seqs.includes(31))
  }
  const assistant = projectTarget(model, 20, detail)
  assert.equal(assistant.tools.length, 0)
  assert.equal(assistant.records[0].preview.content.filter(block => block.type === 'tool-call').length, 3)
  const idOnly = associateEvents([
    { seq: 1, type: 'tool/call', data: { callId: 'id-only', arguments: 'recorded', name: 'read' } },
    { seq: 2, type: 'tool/result', data: { message: { source: { callId: 'id-only' }, content: [] } } },
  ])
  assert.equal(idOnly.activityBySeq.get(1), idOnly.activityBySeq.get(2))
  assert.equal(projectTarget(idOnly, 2, detail).complete, true)
  const partial = associateEvents(history.filter(event => [25, 27].includes(event.seq)))
  const fragment = projectTarget(partial, 27, detail)
  assert.equal(fragment.activity_locator.root_call_id, 'root')
  assert.equal(fragment.tools[0].is_error, true)
  assert.ok(fragment.incomplete_reasons.includes('root_not_observed'))
  const resultOnly = associateEvents(history.filter(event => event.seq === 27))
  assert.equal(projectTarget(resultOnly, 27, detail).tools[0].arguments.file_path, 'missing')
})

test('append result wins; only a single explicit replacement reference locates it, summaries stay summaries', () => {
  const root = projectTarget(model, 40, detail)
  assert.ok(JSON.stringify(root.tools[0].result).includes('Original execution output'))
  assert.ok(!JSON.stringify(root).includes('PRUNED'))
  const replacement = projectTarget(model, 90, detail)
  assert.equal(replacement.requested_seq, 90)
  assert.equal(replacement.records[0].read_seq, 90)
  assert.equal(replacement.records[0].original_result_seq, 40)
  assert.equal(replacement.tools[0].result_seq, 40)
  assert.ok(JSON.stringify(replacement.tools[0].result).includes('Original execution output'))
  assert.deepEqual(replacement.source_seqs, [20, 21, 40, 90])
  const unavailable = projectTarget(associateEvents(history.filter(event => event.seq === 90)), 90, detail)
  assert.equal(unavailable.tools.length, 0)
  assert.ok(unavailable.incomplete_reasons.includes('original_result_not_observed'))
  assert.deepEqual(unavailable.records[0].source_event_seqs, [40])
  const summary = projectTarget(model, 102, detail)
  assert.equal(summary.tools.length, 0)
  assert.equal(summary.activity_locator.activity_id, 'compaction:compact')
  assert.deepEqual(activity(101).events.map(event => event.seq), [100, 101, 102, 103])
  assert.deepEqual(activity(40).events.filter(event => event.type === 'tool/result').map(event => event.seq), [31, 40])
})

test('lifecycle IDs, workflow member seq, failed compaction without summary and unknown facts remain traceable', () => {
  const failed = projectActivity(model, activity(104), options(detail, { coverageComplete: true }))
  assert.equal(failed.records.find(record => record.seq === 105).error_observed, true)
  assert.deepEqual(failed.source_seqs, [104, 105])
  assert.equal(failed.complete, true)
  const partialWorkflow = associateEvents(history.filter(event => [120, 121, 124].includes(event.seq)))
  const memberGap = projectActivity(partialWorkflow, partialWorkflow.activityBySeq.get(120), options(detail, { coverageComplete: true }))
  assert.equal(memberGap.complete, false)
  assert.ok(memberGap.incomplete_reasons.includes('workflow_member_pair_not_observed'))
  const workflow = projectActivity(model, activity(120), options(detail, { coverageComplete: true }))
  assert.deepEqual(workflow.source_seqs, [120, 121, 123, 124])
  const member = workflow.records.find(record => record.seq === 123)
  assert.equal(member.agent_seq, 0)
  assert.equal(member.read_seq, 123)
  assert.equal(member.outcome, 'failed')
  assert.equal(member.error_observed, true)
  assert.equal(workflow.records.find(record => record.seq === 124).stopReason, 'completed')
  assert.deepEqual(activity(110).events.map(event => event.seq), [110, 112])
  assert.notEqual(activity(111), activity(110))
  assert.equal(projectTarget(model, 112, compact).records[0].retry_started_is_not_success, true)
  assert.notEqual(activity(150), activity(151))
  assert.equal(projectTarget(model, 130, compact).records[0].discovery_only, true)
  const unknown = projectTarget(model, 140, detail)
  assert.equal(unknown.records[0].type, 'extension/accepted')
  assert.equal(unknown.records[0].preview.important, 'unknown accepted data')
  assert.equal(Object.keys(EVENT_PROJECTION_STRATEGIES).length, 59)
  for (const event of history) assert.ok(model.activityBySeq.has(event.seq))
  const missingIds = associateEvents([
    { seq: 1, type: 'tool/call', data: { name: 'read' } },
    { seq: 2, type: 'tool/result', data: { message: { content: [] } } },
  ])
  assert.notEqual(missingIds.activityBySeq.get(1), missingIds.activityBySeq.get(2))
})

test('bounded previews never serialize original huge objects and final UTF-8 budget preserves errors and seqs', () => {
  const huge = { x: '😀'.repeat(1000000), toJSON() { throw new Error('original must not be stringified') } }
  const local = associateEvents([{ seq: 1, type: 'extension/accepted', data: huge }])
  const tiny = projectTarget(local, 1, { ...compact, budget: { ...compact.budget, maxStringChars: 2, outputBytes: 1000 } })
  assert.equal(tiny.records[0].preview.x, '😀😀')
  assert.equal(tiny.truncated, true)
  assert.ok(Buffer.byteLength(JSON.stringify(tiny), 'utf8') <= 1000)
  const pair = projectTarget(model, 27, detail)
  const budget = Buffer.byteLength(JSON.stringify(pair), 'utf8') - 300
  const trimmed = projectTarget(model, 27, { ...detail, budget: { ...detail.budget, outputBytes: budget } })
  assert.ok(Buffer.byteLength(JSON.stringify(trimmed), 'utf8') <= budget)
  assert.equal(trimmed.truncated, true)
  assert.equal(trimmed.tools[0].error_observed, true)
  assert.equal(trimmed.tools[0].error_code, 'FS_NOT_FOUND')
  assert.equal(trimmed.tools[0].error_seq, 27)
  assert.deepEqual(trimmed.tools[0].source_seqs, [25, 27])
  assert.equal(trimmed.complete, true)
  assert.throws(() => projectTarget(model, 27, { ...detail, budget: { ...detail.budget, outputBytes: 1 } }), /metadata exceeds/)
  const readGap = projectActivity(model, activity(10), detail)
  assert.ok(readGap.incomplete_reasons.includes('activity_coverage_unproven'))
  assert.equal(readGap.complete, false)
})
